import { Inter } from "next/font/google";
import NavBar from "../../components/Navbar.jsx";
import "./globals.css";
import { getServerSession } from "next-auth";
import { options } from "./api/auth/[...nextauth]/options.js";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children, params }) {
  let session = await getServerSession(options);
  params.session = 'session';
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavBar />
        <div className="main" params={params}>
          {children}
        </div>
      </body>
    </html>
  );
}
